server:
  port: 8001

jwt:
  secret: d2f4b67a1ee3d9c3f1a9725a4cb96e5bb02d4a6e4ac7c38c0bb13e4b4a729b7e3c9ad0b3f6cf58b1a7d15fd3f17e05d7c678ab0418b56d1a79c1f9d4a69a7c6f


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ignite_invest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka